#ifndef __USER_MANAGEMENT_H__
#define __USER_MANAGEMENT_H__

#include <stdio.h>
#include "user.h"

typedef struct _UserArray {
     User* array; // pointer to array (or linked list) of struct User.
     unsigned int length; // number of elements in the (User*) array
     unsigned int capacity;// capacity of array
}UserArray;

extern UserArray user_table;

//initialize the users database
void init_users();

//saves the database of users in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_users(FILE *file);

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_users()
//returns 0 if users were loaded correctly, or an error code otherwise
int load_users(FILE *file);

//adds a user to the ones available to the library
//returns 0 if the user could be added, or an error code otherwise
int add_user(User user);

//find user by username
User* find_user(const char *username);

#endif
