#include "user_management.h"
#include <string.h>
#include <stdlib.h>

UserArray user_table;

//initialize the users database
void init_users()
{
    FILE* fp;
    user_table.length = 0;
    user_table.capacity = 16;
    user_table.array = (User*)malloc(sizeof(User) * user_table.capacity);
    if (user_table.array != NULL)
    {
        fp = fopen("users.txt", "r");
        if (fp != NULL)
        {
            load_users(fp);
            fclose(fp);
        }
    }
}

//saves the database of users in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_users(FILE *file)
{
    unsigned i, j;
    fprintf(file, "%u\n", user_table.length);
    for (i = 0;i < user_table.length; ++i)
    {
        fprintf(file, "%s %s\n", user_table.array[i].username, user_table.array[i].password);
        fprintf(file, "%u", user_table.array[i].borrow_length);
        for (j = 0;j < user_table.array[i].borrow_length; ++j)
        {
            fprintf(file, " %u", user_table.array[i].borrow_arr[j]);
        }
        fprintf(file, "\n");
    }
    return 0;
}

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_users()
//returns 0 if users were loaded correctly, or an error code otherwise
int load_users(FILE *file)
{
    unsigned length, i, j;
    char line[1024];
    char username[64], password[64];
    int code;
    User user;

    user_table.length = 0;
    fscanf(file, "%u", &length);
    for (i = 0;i < length; ++i)
    {
        fscanf(file, "%s%s", username, password);
        user.username = strdup(username);
        user.password = strdup(password);
        fscanf(file, "%u", &user.borrow_length);
        for (j = 0;j < user.borrow_length; ++j)
        {
            fscanf(file, "%u", &user.borrow_arr[j]);
        }
        add_user(user);
    }
    return 0;
}

// extend space
static int extend_space(UserArray *user_arr)
{
    unsigned i;
    User* new_space;
    unsigned new_capacity = user_arr->capacity * 2;
    if (new_capacity == 0)
    {
        new_capacity = 16;
    }
    new_space = (User*)malloc(sizeof(User) * new_capacity);
    if (new_space == NULL)
    {
        return -1;
    }
    for (i = 0;i < user_arr->length; ++i)
    {
        new_space[i] = user_arr->array[i];
    }
    if (user_arr->array != NULL)
    {
        free(user_arr->array);
    }
    user_arr->array = new_space;
    user_arr->capacity = new_capacity;
    return 0;
}

//adds a user to the ones available to the library
//returns 0 if the user could be added, or an error code otherwise
int add_user(User user)
{
    if (user_table.length == user_table.capacity)
    {
        if (-1 == extend_space(&user_table))
        {
            return -1;
        }
    }
    user_table.array[user_table.length] = user;
    ++user_table.length;
    return 0;
}

//find user by username
User* find_user(const char *username)
{
    unsigned i;
    if (strcmp("librarian", username) == 0)
    {
        return (User*)1;
    }
    for (i = 0;i < user_table.length; ++i)
    {
        if (strcmp(user_table.array[i].username, username) == 0)
        {
            return &user_table.array[i];
        }
    }
    return NULL;
}